[supervisord]
nodaemon=true

[program:uvicorn]
command=uvicorn apis.main:app --host 0.0.0.0 --port 8000
directory=/app
environment=NOTIFICATION_WORKER_ENABLED="true"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
